<?php require __dir__."/layout/app.phtml"?>

<div class="container">
<div class="col-md-4">
    <div class="panel panel-primary">
    <div class="panel-heading"><strong>Users currently Online</strong></div>
    <div class="panel-body">
    <?php if (is_array($active) && count($active)):?>
        <div class='list-group'>
        <?php foreach($active as $user):?>
            <li class='list-group-item'>
            <h4 class='list-group-item-heading'>
                <?=strlen($user['uname']) ? $user['uname'] : "unknown"?>
                <br />
                <small>
                    Station: <code><?=strlen($user['station'])>25?substr($user['station'],0,23)."..":$user['station']?></code><br />
                    <i><?=date('d. m. Y H:i:s',  $user['chtime'])?></i>
                </small>
            </h4>
            </li>
        <?php endforeach?>
        </div>
    <?php else:?>
        <span class='text-muted'>None</span>
    <?php endif?>
    </div>
    </div>
</div>
<div class="col-md-8">
    <div class="panel panel-default">
    <div class="panel-heading"><strong>Raw Data</strong></div>
    <div class="panel-body">
    <?php if(is_array($raw) && count($raw)):?>
        <ul class='list-group'>
        <?php foreach($raw as $user):?>
            <li class='list-group-item'>
                <kbd><?=$user['mode']?></kbd>
                <?=strlen($user['uname']) ? $user['uname'] : "unknown"?>@<?=$user['station']?>
                <small>
                    <i class="pull-right"><?=date('d. m. Y H:i:s',  $user['chtime'])?></i>
                </small>
            </li>
        <?php endforeach?>
        </ul>
    <?php else:?>
        <span class='text-muted'>None</span>
    <?php endif?>
    </div>
    </div>
</div>
</div>
</div>