<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="fav/favicon.png">
    <title>Audit</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>
<body>
<?php require_once "navbar.phtml"?>
<?php if(is_array(@$error) || is_array(@$status)):?>
<div class="container">
<div class="col-md-6 col-md-offset-3">
<?php if (is_array(@$error)):?>
<?php foreach($error as $err):?>
    <div class='alert alert-danger'>
        <strong><?=$err[0]?></strong> <?=$err[1]?>
    </div>
<?php endforeach?>
<?php endif; if (is_array(@$status)):?>
<?php foreach($status as $line):?>
    <div class='alert alert-success'>
        <strong><?=$line[0]?></strong> <?=$line[1]?>
    </div>
<?php endforeach?>
<?php endif?>
</div>
</div>
<?php endif?>